### PR TITLE
build images that have the snap binaries included.

### LINKED ISSUE #7: images assume that containers have internet access
The images try and pull down the latest snap binaries when the container starts.  If the containers are running inside environments with limited or no internet access, then the containers cant start.

Why cant the Dockerfiles just pull the binaries into the docker image at build time and tag the image with the build version.

### PR DESCRIPTION
**Pull request by woodsaj**
fixes #7

### CODE REVIEW

**Comment by IRCody** [comment]
cc: @intelsdi-x/plugin-maintainers

**Comment by woodsaj** [comment]
#10 looks to be doing the same thing,  though looks incomplete.

**Comment by IRCody** [comment]
Ok. It looks like @nanliu left a comment on #7 about why it's taking a little bit of time to get it completed.

**Comment by nanliu** [comment]
We have fixed the blocking issue, and I'll try to circle back and update #10 next week.

**Comment by nanliu** [comment]
Addressed in #10. Closing this PR per comment in #7.

**Pull request closed without merging**
